version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    extra_hosts:
      - "host.docker.internal:host-gateway"      
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports: 
       - '9092:9092'
    extra_hosts:
      - "host.docker.internal:host-gateway"   
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

# OneBank CPT Service and Database
  onebankcpt:
    image: 'onebankcpt'
    ports:
      - '8080:8080'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/obcpt_db
    restart: on-failure  
    depends_on:
      - kafka
      - db

  db:
    image: mysql:latest
    container_name: db
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'obcpt_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./init/onebankcpt_db:/docker-entrypoint-initdb.d    

# OneBank Hub Service.and Database
  onebankhub:
    image: 'onebankhub'
    ports:
      - '8081:8081'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - SPRING_DATASOURCE_URL=jdbc:mysql://onebankhub_db:3306/obhub_db
    depends_on:
      - kafka
      - onebankhub_db
    restart: on-failure

  onebankhub_db:
    image: mysql:latest
    container_name: onebankhub_db
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'obhub_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./init/onebankhub_db:/docker-entrypoint-initdb.d
